name: dotnet package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x'
    - name: Install dependencies
      run: | 
        cd src 
        dotnet restore
        cd ../tests
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build
        cd ../tests
        dotnet build
    - name: Test with the dotnet CLI
      run: dotnet test